// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqizbavkfkpdqptqhkzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xaXpiYXZrZmtwZHFwdHFoa3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxODMxNzcsImV4cCI6MjA3Mjc1OTE3N30.6nJPwHfqLJxxmtCC3IJyiIK879bwY3MY1Px0XMyeg_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});